### ISSUE TITLE
Server returned HTTP response code: 500 for URL

### ISSUE THREAD

**Issue by njmube** [kyojinindie/indie-sat-ws#1]
Buen día.

Al ejecutar el proyecto obtengo el mensaje de error en todas las ocasiones: Server returned HTTP response code: 500 for URL: https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc

¿Que estoy haciendo mal?

**Comment by kyojinindie** [comment]
> Buen día.
> 
> Al ejecutar el proyecto obtengo el mensaje de error en todas las ocasiones: Server returned HTTP response code: 500 for URL: https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc
> 
> ¿Que estoy haciendo mal?
> 
> ![idea64_2021-09-01_23-50-59](https://user-images.githubusercontent.com/7807456/131783822-24a1b27b-099a-4bdf-9c72-2c824ce4ecb7.png)

Buen día, por el error probablemente el servicio del sat estaba abajo cuando intentaste correr la aplicación, la URL es correcta, por lo que el response code 500 nos dice que el servidor tiene problemas, de todos modos reviso la aplicación para ver si puedo replicar el problema

**Comment by njmube** [comment]
Hola.

Gracias.
