### ISSUE TITLE
 Id Packages: null

### ISSUE THREAD

**Issue by njmube** [kyojinindie/indie-sat-ws#2]
Buen día.

**Comment by kyojinindie** [comment]
> Buen día.
> 
> Al ejecutar el proyecto me muestra Id Packages: null, no se en donde pueda estar mi error ¿que estaré haciendo mal?.
> 
> ![chrome_2021-09-02_13-05-52](https://user-images.githubusercontent.com/7807456/131895152-bacdccad-9964-44cf-a8d6-45a3aa2316fa.png)
> 
> ![idea64_2021-09-02_12-59-34](https://user-images.githubusercontent.com/7807456/131895194-ee215e24-7513-4f08-8b9b-0ac46938d3cf.png)
> 
> ![idea64_2021-09-02_13-00-13](https://user-images.githubusercontent.com/7807456/131895175-e3fa2804-a605-41d2-b860-b6c6168fd88d.png)

Es posible que alguno de estos campos del archivo util falte o esten incorrectos:

FILEPATHPFX
FILEPATHCER
RFCAPPLICANT
URLVERIFYREQUEST
URLVERIFYREQUESTACTION

**Comment by njmube** [comment]
Gracias por tu respuesta.

Los campos que indicas si tienen valores asignados, adjunto la captura.

Al mostrar en el LOG me di cuenta que el XML **PeticionDescargaMasivaTercerosEntrada** tiene IdPaquete="null" en lugar de un valor.

![idea64_2021-09-02_16-05-37](https://user-images.githubusercontent.com/7807456/131916190-85c02122-b1bd-45a8-b172-175617a397ee.png)

![chrome_2021-09-02_16-02-12](https://user-images.githubusercontent.com/7807456/131916191-4e7d020e-e8f5-4368-a26c-ae1cbb8b20e8.png)
